<a href="https://colab.research.google.com/github/Huii0529/Data-Science-Project/blob/main/PROJECT1_FANGJIAHUI_P167347.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **PART 2 - LISTS, DICTIONARIES AND LOOPING**

In [ ]:
fav_cities = {
    "Kuala Lumpur": {"country": "Malaysia", "population": 8.9, "landmarks": ["Petronas Twin Towers", "Batu Caves", "Merdeka Square"], "dishes": ["Nasi Lemak", "Laksa", "Satay"]},
    "Jakarta": {"country": "Indonesia", "population": 41.9, "landmarks": ["Monas", "Kota Tua", "Taman Mini Indonesia Indah"], "dishes": ["Nasi Goreng", "Sate Ayam", "Rendang"]},
    "Singapore": {"country": "Singapura", "population": 6.11, "landmarks": ["Marina Bay Sands", "Gardens by the Bay", "Merlion Park"], "dishes": ["Chilli Crab", "Hainanese Chicken Rice", "Laksa"]},
    "Bangkok": {"country": "Thailand", "population": 11.4, "landmarks": ["Grand Palace", "Wat Arun", "Chatuchak Weekend Market"], "dishes": ["Pad Thai", "Tom Yum Goong", "Green Curry"]},
    "Ho Chi Minh City": {"country": "Vietnam", "population": 9.8, "landmarks": ["Hoan Kiem Lake", "Temple of Literature", "Old Quarter"], "dishes": ["Pho", "Banh Mi", "Cha Ca"]}
}

for city_name, info in fav_cities.items():
    print("\nCity: {}".format(city_name))
    print("Country: {}".format(info['country']))
    print("Population: {:.1f} million".format(info['population']))

    print("The Famous Landmarks at {}:".format(city_name))
    for landmark in info['landmarks']:
        print("    - {}".format(landmark))

    print("Popular Local Dishes:")
    for dish in info['dishes']:
        print("    - {}".format(dish))


City: Kuala Lumpur
Country: Malaysia
Population: 8.9 million
The Famous Landmarks at Kuala Lumpur:
    - Petronas Twin Towers
    - Batu Caves
    - Merdeka Square
Popular Local Dishes:
    - Nasi Lemak
    - Laksa
    - Satay

City: Jakarta
Country: Indonesia
Population: 41.9 million
The Famous Landmarks at Jakarta:
    - Monas
    - Kota Tua
    - Taman Mini Indonesia Indah
Popular Local Dishes:
    - Nasi Goreng
    - Sate Ayam
    - Rendang

City: Singapore
Country: Singapura
Population: 6.1 million
The Famous Landmarks at Singapore:
    - Marina Bay Sands
    - Gardens by the Bay
    - Merlion Park
Popular Local Dishes:
    - Chilli Crab
    - Hainanese Chicken Rice
    - Laksa

City: Bangkok
Country: Thailand
Population: 11.4 million
The Famous Landmarks at Bangkok:
    - Grand Palace
    - Wat Arun
    - Chatuchak Weekend Market
Popular Local Dishes:
    - Pad Thai
    - Tom Yum Goong
    - Green Curry

City: Ho Chi Minh City
Country: Vietnam
Population: 9.8 million
The Famous 

### **PART 3 - FUNCTIONS AND CLASSES**



In [ ]:
# Parent class
class PetFood:
    def __init__(self, name, category, price, monthly_sales):
        self.name = name
        self.category = category
        self.price = price
        self.monthly_sales = monthly_sales

    def total_sales_revenue(self):
        return self.price * self.monthly_sales - (self.price * 0.35)

    def display_info(self):
        return (
            "Product Formula: {}\n".format(self.name) +
            "Category: {}\n".format(self.category) +
            "Price: MYR{:.2f}\n".format(self.price) +
            "Monthly Sales: {}\n".format(self.monthly_sales) +
            "Total Sales Revenues: MYR{:.2f}".format(self.total_sales_revenue())
        )

# Child class for cat food
class CatFood(PetFood):
    def __init__(self, name, price, type_food, monthly_sales):
        super().__init__(name, "Cat Food", price, monthly_sales)
        self.type_food = type_food

    def display_info(self):
        return (
            super().display_info() +
            "\nType: {}".format(self.type_food)
        )

# Child class for dog food
class DogFood(PetFood):
    def __init__(self, name, price, type_food, monthly_sales):
        super().__init__(name, "Dog Food", price, monthly_sales)
        self.type_food = type_food

    def display_info(self):
        return (
            super().display_info() +
            "\nType: {}".format(self.type_food)
        )

In [ ]:
# Create instances of CatFood
cat_foods = [
    CatFood("Chicken & Pomegranate", 130, "Dry", 150),
    CatFood("Tuna & Shrimp", 8.5, "Treats", 120),
    CatFood("Herring & Orange", 125, "Dry", 130),
    CatFood("Duck & Cranberry", 8.5, "Wet", 110),
    CatFood("Quail & Coconut", 150, "Dry", 140)
]

# Create instances of DogFood
dog_foods = [
    DogFood("Lamb & Blueberry", 130, "Dry", 160),
    DogFood("Chicken & Pomegranate", 130, "Wet", 150),
    DogFood("Cod & Pumpkin", 10, "Wet", 140),
    DogFood("Salmon & Spelts", 100, "Treats", 130),
    DogFood("Duck & Coconut", 12, "Wet", 120)
]

# Display info for cat food
print("Top 4 Monthly Sales Revenue's Cat Food:\n")
for cat in cat_foods:
    print(cat.display_info())
    print("\n")

# Display info for dog food
print("-----------------------------------------")
print("Top 4 Monthly Sales Revenue's Dog Food:\n")
for dog in dog_foods:
    print(dog.display_info())
    print("\n")


Top 4 Monthly Sales Revenue's Cat Food:

Product Formula: Chicken & Pomegranate
Category: Cat Food
Price: MYR130.00
Monthly Sales: 150
Total Sales Revenues: MYR19454.50
Type: Dry


Product Formula: Tuna & Shrimp
Category: Cat Food
Price: MYR8.50
Monthly Sales: 120
Total Sales Revenues: MYR1017.02
Type: Treats


Product Formula: Herring & Orange
Category: Cat Food
Price: MYR125.00
Monthly Sales: 130
Total Sales Revenues: MYR16206.25
Type: Dry


Product Formula: Duck & Cranberry
Category: Cat Food
Price: MYR8.50
Monthly Sales: 110
Total Sales Revenues: MYR932.02
Type: Wet


Product Formula: Quail & Coconut
Category: Cat Food
Price: MYR150.00
Monthly Sales: 140
Total Sales Revenues: MYR20947.50
Type: Dry


-----------------------------------------
Top 4 Monthly Sales Revenue's Dog Food:

Product Formula: Lamb & Blueberry
Category: Dog Food
Price: MYR130.00
Monthly Sales: 160
Total Sales Revenues: MYR20754.50
Type: Dry


Product Formula: Chicken & Pomegranate
Category: Dog Food
Price: MYR1

### **PART 4 - FILES AND EXCEPTION**

In [ ]:
try:
    with open('/content/sample_data/movie.txt') as file_object:
      contents = file_object.read()
      print(contents)
      print("\n")

    with open('/content/sample_data/sport.txt') as file_object:
      contents = file_object.read()
      print(contents)
except FileNotFoundError:
    print("Error: One or both files (movie.txt, sport.txt) not found. Please ensure they exist in /content/sample_data/")

Inception
Titanic
The Dark Knight
Avengers: Endgame
Interstellar
These are some critically acclaimed and popular movies.
They represent various genres and storytelling styles.
From mind-bending sci-fi to historical dramas, there's a movie for everyone.
Each film has left a significant mark on cinema history.
Enjoy exploring these cinematic masterpieces.



Football
Badminton
Basketball
Tennis
Swimming
These are some of the most widely played and followed sports globally.
They encompass team sports, individual events, and aquatic activities.
From the pitch to the court, and the track to the pool, these sports offer diverse challenges.
Athletes in these disciplines often display extraordinary skill and dedication.
Discover the excitement and competition of these popular athletic pursuits.



In [ ]:
movie_descriptions = ['These are some critically acclaimed and popular movies.', 'They represent various genres and storytelling styles.', "From mind-bending sci-fi to historical dramas, there's a movie for everyone.", 'Each film has left a significant mark on cinema history.', 'Enjoy exploring these cinematic masterpieces.']
sport_descriptions = ['These are some of the most widely played and followed sports globally.', 'They encompass team sports, individual events, and aquatic activities.', 'From the pitch to the court, and the track to the pool, these sports offer diverse challenges.', 'Athletes in these disciplines often display extraordinary skill and dedication.', 'Discover the excitement and competition of these popular athletic pursuits.']

# Append descriptions to movie.txt
with open('/content/sample_data/movie.txt', 'a') as file_object:
    file_object.write('\n') # Add a newline for readability
    for desc in movie_descriptions:
        file_object.write(desc + '\n')
print("Movie descriptions appended to movie.txt")

# Append descriptions to sport.txt
with open('/content/sample_data/sport.txt', 'a') as file_object:
    file_object.write('\n') # Add a newline for readability
    for desc in sport_descriptions:
        file_object.write(desc + '\n')
print("Sport descriptions appended to sport.txt")

Movie descriptions appended to movie.txt
Sport descriptions appended to sport.txt


In [ ]:
movie_names = []
movie_descriptions = []

sport_names = []
sport_descriptions = []

try:
    with open('/content/sample_data/movie.txt', 'r') as file_object:
        all_movie_lines = [line.strip() for line in file_object if line.strip()]
        if len(all_movie_lines) >= 10:
            movie_names = all_movie_lines[0:5]
            movie_descriptions = all_movie_lines[5:10]
        elif len(all_movie_lines) > 0: # If only names are present or partial descriptions
            movie_names = all_movie_lines

    with open('/content/sample_data/sport.txt', 'r') as file_object:
        all_sport_lines = [line.strip() for line in file_object if line.strip()]
        if len(all_sport_lines) >= 10:
            sport_names = all_sport_lines[0:5]
            sport_descriptions = all_sport_lines[5:10]
        elif len(all_sport_lines) > 0: # If only names are present or partial descriptions
            sport_names = all_sport_lines

except FileNotFoundError:
    print("Error: One or both files (movie.txt, sport.txt) not found.")

print("\n--- Recommended Movies ---")
for i in range(len(movie_names)):
    name = movie_names[i]
    description = movie_descriptions[i] if i < len(movie_descriptions) else "No description available."
    print("Movie Name: {}\nDescription: {}\n".format(name, description))

print("\n--- Recommended Sports ---")
for i in range(len(sport_names)):
    name = sport_names[i]
    description = sport_descriptions[i] if i < len(sport_descriptions) else "No description available."
    print("Sport: {}\nDescription: {}\n".format(name, description))



--- Recommended Movies ---
Movie Name: Inception
Description: These are some critically acclaimed and popular movies.

Movie Name: Titanic
Description: They represent various genres and storytelling styles.

Movie Name: The Dark Knight
Description: From mind-bending sci-fi to historical dramas, there's a movie for everyone.

Movie Name: Avengers: Endgame
Description: Each film has left a significant mark on cinema history.

Movie Name: Interstellar
Description: Enjoy exploring these cinematic masterpieces.


--- Recommended Sports ---
Sport: Football
Description: These are some of the most widely played and followed sports globally.

Sport: Badminton
Description: They encompass team sports, individual events, and aquatic activities.

Sport: Basketball
Description: From the pitch to the court, and the track to the pool, these sports offer diverse challenges.

Sport: Tennis
Description: Athletes in these disciplines often display extraordinary skill and dedication.

Sport: Swimming
Desc

### **PART 5 - NUMPY**

In [ ]:
import numpy as np

# First set of arrays
A = np.random.rand(5)
B = np.random.rand(3, 3)
C = np.random.rand(2, 4)
D = np.random.rand(4, 2)
E = np.random.rand(5, 5)

# Second set of arrays
F = np.random.rand(5)
G = np.random.rand(3, 3)
H = np.random.rand(2, 4)
I = np.random.rand(4, 2)
J = np.random.rand(5, 5)

# Print each array to display its contents
print("Array A (1D, size 5):\n{}".format(A))
print("\nArray B (2D, 3x3):\n{}".format(B))
print("\nArray C (2D, 2x4):\n{}".format(C))
print("\nArray D (2D, 4x2):\n{}".format(D))
print("\nArray E (2D, 5x5):\n{}".format(E))
print("\nArray F (1D, size 5):\n{}".format(F))
print("\nArray G (2D, 3x3):\n{}".format(G))
print("\nArray H (2D, 2x4):\n{}".format(H))
print("\nArray I (2D, 4x2):\n{}".format(I))
print("\nArray J (2D, 5x5):\n{}".format(J))

Array A (1D, size 5):
[0.91688115 0.07418287 0.4442987  0.45231545 0.74989141]

Array B (2D, 3x3):
[[0.29563877 0.89388736 0.02631803]
 [0.65716162 0.35158684 0.98897646]
 [0.07066334 0.87206778 0.78735905]]

Array C (2D, 2x4):
[[0.00270325 0.61401565 0.04626899 0.98326701]
 [0.86640899 0.77507183 0.40636947 0.6676784 ]]

Array D (2D, 4x2):
[[0.04154939 0.60840571]
 [0.53287732 0.18462141]
 [0.25174946 0.01946871]
 [0.33692161 0.23454849]]

Array E (2D, 5x5):
[[0.85428072 0.77623157 0.23551116 0.4198326  0.57301488]
 [0.20508863 0.5824929  0.56239579 0.75166579 0.76179392]
 [0.08465322 0.9981614  0.1901823  0.02373225 0.97425289]
 [0.94798762 0.00966608 0.60925283 0.46608345 0.93981636]
 [0.1247431  0.03591229 0.16802061 0.20867114 0.14861808]]

Array F (1D, size 5):
[0.44172368 0.84768718 0.26467651 0.03753784 0.68348611]

Array G (2D, 3x3):
[[0.6463564  0.31487999 0.50963744]
 [0.46300787 0.13861316 0.01484223]
 [0.21096396 0.56772007 0.23992424]]

Array H (2D, 2x4):
[[0.01424263 0.5

In [ ]:
print("\n--- 1. Perform operation on single array ---")

# Sum of all elements
print("\nSum of elements in A: {}".format(np.sum(A)))

# Mean of all elements
print("Mean of elements in B: {}".format(np.mean(B)))

# Maximum element
print("Maximum element in C: {}".format(np.max(C)))

# Minimum element
print("Minimum element in D: {}".format(np.min(D)))

# Standard deviation
print("Standard deviation of E: {}".format(np.std(E)))

# Reshape array A to (1, 5)
reshaped_A = A.reshape(1, 5)
print("\nReshaped A (1x5):\n{}".format(reshaped_A))

# Transpose array C
transposed_C = C.T
print("\nTransposed C (4x2):\n{}".format(transposed_C))

# Sort array A
sorted_A = np.sort(A)
print("\nSorted A: {}".format(sorted_A))

# Find unique elements
rand_arr_with_dups = np.array([1, 2, 2, 3, 4, 4, 5])
unique_elements = np.unique(rand_arr_with_dups)
print("\nUnique elements in [1, 2, 2, 3, 4, 4, 5]: {}".format(unique_elements))

# Square root of elements in A
sqrt_A = np.sqrt(A)
print("\nSquare root of elements in A: {}".format(sqrt_A))

# Absolute value of elements
abs_val_A = np.abs(A - 0.5)
print("\nAbsolute values of (A - 0.5): {}".format(abs_val_A))

# Round elements of A to 2 decimal places
rounded_A = np.round(A, 2)
print("\nRounded A (2 decimal places): {}".format(rounded_A))



--- 1. Perform operation on single array ---

Sum of elements in A: 2.637569566796496
Mean of elements in B: 0.5492954739540671
Maximum element in C: 0.9832670056739465
Minimum element in D: 0.019468714578224744
Standard deviation of E: 0.3331736924506809

Reshaped A (1x5):
[[0.91688115 0.07418287 0.4442987  0.45231545 0.74989141]]

Transposed C (4x2):
[[0.00270325 0.86640899]
 [0.61401565 0.77507183]
 [0.04626899 0.40636947]
 [0.98326701 0.6676784 ]]

Sorted A: [0.07418287 0.4442987  0.45231545 0.74989141 0.91688115]

Unique elements in [1, 2, 2, 3, 4, 4, 5]: [1 2 3 4 5]

Square root of elements in A: [0.95753911 0.27236532 0.66655735 0.67254401 0.86596271]

Absolute values of (A - 0.5): [0.41688115 0.42581713 0.0557013  0.04768455 0.24989141]

Rounded A (2 decimal places): [0.92 0.07 0.44 0.45 0.75]


In [ ]:
print("\n--- 2. Perform operation on two arrays of same size ---")

# Addition of A and F
print("\nElement-wise addition (A + F):\n{}".format(np.add(A, F)))

# Subtraction of G from B
print("\nElement-wise subtraction (B - G):\n{}".format(np.subtract(B, G)))

# Multiplication of C and H
print("\nElement-wise multiplication (C * H):\n{}".format(np.multiply(C, H)))

# Division of E by J
epsilon = 1e-8
print("\nElement-wise division (E / J):\n{}".format(np.divide(E, J + epsilon)))

# Power (F to the power of A)
print("\nElement-wise power (F ** A):\n{}".format(np.power(F, A)))

# Comparison (B > G)
print("\nElement-wise comparison (B > G):\n{}".format(np.greater(B, G)))

# Minimum of C and H
print("\nElement-wise minimum (np.minimum(C, H)):\n{}".format(np.minimum(C, H)))

print("\n--- 3. Perform operation on two arrays of different size (Dot Products) ---")
# Dot product of C (2x4) and D (4x2)
dot_product_CD = np.dot(C, D)
print("\nDot product of C and D (2x4 @ 4x2 = 2x2):\n{}".format(dot_product_CD))



--- 2. Perform operation on two arrays of same size ---

Element-wise addition (A + F):
[1.35860482 0.92187005 0.70897521 0.48985328 1.43337751]

Element-wise subtraction (B - G):
[[-0.35071763  0.57900737 -0.4833194 ]
 [ 0.19415376  0.21297369  0.97413423]
 [-0.14030062  0.30434771  0.5474348 ]]

Element-wise multiplication (C * H):
[[3.85013936e-05 3.60940140e-01 4.41037926e-02 4.55387546e-01]
 [6.31234187e-01 3.41797211e-01 2.24618686e-01 3.14374173e-01]]

Element-wise division (E / J):
[[1.39210395e+00 2.66978540e+00 3.44647372e-01 3.06364536e+00
  8.58558383e-01]
 [3.55308635e-01 6.67321648e-01 7.59324783e-01 2.12549667e+00
  1.68459584e+00]
 [2.98308082e-01 9.63654625e+00 4.02327291e-01 8.08177316e-02
  2.18346747e+00]
 [1.69106873e+00 5.33768899e-02 2.42354211e+00 1.00258575e+00
  6.20323780e+01]
 [5.60274171e-01 5.43900230e-02 4.25820479e-01 2.59714381e-01
  1.87585724e+00]]

Element-wise power (F ** A):
[0.47276503 0.98781658 0.55400438 0.22657418 0.75173577]

Element-wise co